//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ts() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Properties.ts", typeof(ts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose format Logs file:
        ///1 : Json
        ///2 : Xml
        ///q : Quit.
        /// </summary>
        internal static string ChooseFormatLogs {
            get {
                return ResourceManager.GetString("ChooseFormatLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose save slots (e.g., 1;2;3) or &apos;q&apos; to Quit:.
        /// </summary>
        internal static string ChooseSaveSlots {
            get {
                return ResourceManager.GetString("ChooseSaveSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination directory path for Slot {0}:.
        /// </summary>
        internal static string ChooseSlotDestination {
            get {
                return ResourceManager.GetString("ChooseSlotDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose current directory for Slot {0}:.
        /// </summary>
        internal static string ChooseSlotSourceFile {
            get {
                return ResourceManager.GetString("ChooseSlotSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleting Slot {0}.
        /// </summary>
        internal static string DeletingSlot {
            get {
                return ResourceManager.GetString("DeletingSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Available save slots:.
        /// </summary>
        internal static string DisplayAvailableSaveSlots {
            get {
                return ResourceManager.GetString("DisplayAvailableSaveSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Empty.
        /// </summary>
        internal static string EmptySlot {
            get {
                return ResourceManager.GetString("EmptySlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in creation of file.
        /// </summary>
        internal static string ErrorCreationFile {
            get {
                return ResourceManager.GetString("ErrorCreationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error: One or more selected slots are empty or non-empty..
        /// </summary>
        internal static string ErrorSelectedSlotsEmptyNonEmpty {
            get {
                return ResourceManager.GetString("ErrorSelectedSlotsEmptyNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid input!.
        /// </summary>
        internal static string InvalidInputLogsFormat {
            get {
                return ResourceManager.GetString("InvalidInputLogsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid input! Please enter &apos;1&apos; to Save or &apos;2&apos; to Delete..
        /// </summary>
        internal static string InvalidInputSaveDelete {
            get {
                return ResourceManager.GetString("InvalidInputSaveDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2 : Delete.
        /// </summary>
        internal static string OptionDelete {
            get {
                return ResourceManager.GetString("OptionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1 : Save.
        /// </summary>
        internal static string OptionSave {
            get {
                return ResourceManager.GetString("OptionSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Slot {0} is empty !.
        /// </summary>
        internal static string SaveSelectedSlotEmpty {
            get {
                return ResourceManager.GetString("SaveSelectedSlotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saving Slot {0}.
        /// </summary>
        internal static string SavingSlot {
            get {
                return ResourceManager.GetString("SavingSlot", resourceCulture);
            }
        }
    }
}
