name: EasySave.Tests

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: EasySaveWPF

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore EasySaveWPF/EasySaveWPF

      - name: Build
        run: |
          cd EasySaveWPF/EasySaveWPF/EasySave.Tests
          dotnet build --configuration Release --no-restore

      - name: Test
        run: |
          cd EasySaveWPF/EasySaveWPF/EasySave.Tests
          dotnet test --no-build --verbosity normal --configuration Release EasySave.Tests.csproj
